Feature/dto
gamedoora/gamedoora-user-services pull request #25
Opened 2023-06-26 03:31 UTC by picksitquick

@aprajshekhar please review
Fixes #

## Proposed Changes

  - Added implementation of Mapper in Gamedoora UserService based on the changes made on Gamedoora Models.
  - Made changes in pom.xml based on run configs
  - APIs now return Dto instead of Dao
  - Please provide any feedback regarding any changes to be made.

2023-06-26 04:37 UTC, aprajshekhar requested changes
Thanks for the PR.  Just two suggestions:
- Using getters would be a better approach.
- Let's start using setter based autowiring.

2023-06-26 04:37 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/userservices/assembler/RolesServicesAssembler.java
> +  @Autowired private RolesMapper rolesMapper;
Let's start using setter based autowiring.

2023-06-26 04:37 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/userservices/assembler/RolesServicesAssembler.java
> +    if (name == null) rolesRepository.findAll().forEach(roles -> roleDTOList.add(rolesMapper.roleToRoleDto(roles)));
Using getters would be a better approach.

2023-06-26 04:37 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/userservices/assembler/SkillsServicesAssembler.java
> +  @Autowired
Let's start using setter based autowiring.

2023-06-26 04:37 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/userservices/assembler/SkillsServicesAssembler.java
> +      skillsRepository.findAll().forEach(skills -> skillsDTOList.add(skillsMapper.skillsToSkillsDTO(skills)));
Using getters would be a better approach.

2023-06-30 06:38 UTC, picksitquick commented
@aprajshekhar 
I have made the requested changes, private fields now uses getter/setters.
Please review it, let me know if any changes are needed, or else we are good to merge this PR

2023-06-30 06:44 UTC, aprajshekhar approved these changes
Thanks for the changes. Approved and merging

2023-06-30 06:44 UTC, merged