Fixed UserRepositoryTest
gamedoora/gamedoora-user-services pull request #33
Opened 2023-07-27 13:44 UTC by picksitquick

Fixes #
Fixed UserRepositoryTest, now we don't see any SQL errors in the logs.
## Proposed Changes

  - facing conflicts with certain model class, a PR has been raised for gamedoora-models as well.

2023-07-28 03:30 UTC, aprajshekhar requested changes
Thanks for quick turnaround. Just one comment.

2023-07-28 03:30 UTC, aprajshekhar commented on src/test/resources/application.properties
> +userservice.db.primary.hibernate.dialect=org.hibernate.dialect.H2Dialect
Since configs are not using userservice prefix anymore, the prefix can be removed.

2023-08-06 14:12 UTC, picksitquick commented
@aprajshekhar 
If everything else looks good, then:
this can be merged as the test properties will be updated with PR #35

2023-08-06 14:31 UTC, aprajshekhar approved these changes

2023-08-06 14:31 UTC, merged